import os
import glob
from bs4 import BeautifulSoup
import re

SOURCE_DIR = '/home/anuruprkris/Project/TASM/stitch_technopark_kerala_asset_management_system_v3'
VUE_VIEWS_DIR = '/home/anuruprkris/Project/TASM/tasm-frontend/src/views'
ROUTER_FILE = '/home/anuruprkris/Project/TASM/tasm-frontend/src/router/index.ts'

os.makedirs(VUE_VIEWS_DIR, exist_ok=True)

def snake_to_pascal(snake_str):
    return ''.join(word.title() for word in snake_str.split('_'))

routes = []

# Get all directories in the source
dirs = [d for d in os.listdir(SOURCE_DIR) if os.path.isdir(os.path.join(SOURCE_DIR, d))]

for d in dirs:
    if d == 'technopark_kerala_ams_design_system':
        continue
    
    html_path = os.path.join(SOURCE_DIR, d, 'code.html')
    if not os.path.exists(html_path):
        continue
        
    with open(html_path, 'r', encoding='utf-8') as f:
        soup = BeautifulSoup(f.read(), 'html.parser')
        
    main_content = soup.find('main')
    
    if main_content:
        # Strip out the ml-[248px] classes from main if they exist to fit the new AppLayout
        if main_content.get('class'):
            main_content['class'] = [c for c in main_content['class'] if not c.startswith('ml-[248px]') and not c.startswith('pt-[60px]')]
            
        vue_name = snake_to_pascal(d)
        route_path = d.replace('_', '-')
        
        # Write Vue file
        vue_content = f"""<template>
{main_content.prettify()}
</template>

<script setup lang="ts">
// Autogenerated from {d}
</script>
"""
        with open(os.path.join(VUE_VIEWS_DIR, f"{vue_name}.vue"), 'w', encoding='utf-8') as f:
            f.write(vue_content)
            
        routes.append({
            'path': route_path,
            'name': vue_name,
            'component': vue_name
        })

# Generate Router file
routes_str = ",\n        ".join([f"{{ path: '{r['path']}', name: '{r['name']}', component: () => import('../views/{r['component']}.vue') }}" for r in routes])

router_content = f"""import {{ createRouter, createWebHistory }} from 'vue-router'
import AppLayout from '../components/AppLayout.vue'

const router = createRouter({{
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [
    {{
      path: '/',
      component: AppLayout,
      children: [
        {{
          path: '',
          name: 'Dashboard',
          component: () => import('../views/Dashboard.vue')
        }},
        {routes_str}
      ]
    }}
  ]
}})

export default router
"""

with open(ROUTER_FILE, 'w', encoding='utf-8') as f:
    f.write(router_content)

print(f"Successfully migrated {len(routes)} views!")
