version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - unconvert
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 15

run:
  timeout: 5m
