import type { RouteRecordRaw } from 'vue-router';

interface AppRouteDefinition {
  path: string;
  name: string;
  title: string;
  icon?: string;
  showInSidebar?: boolean;
  component: NonNullable<RouteRecordRaw['component']>;
}

export const appRoutes: AppRouteDefinition[] = [
  {
    path: '',
    name: 'Dashboard',
    title: 'Dashboard',
    icon: 'dashboard',
    showInSidebar: true,
    component: () => import('../views/Dashboard.vue'),
  },
  {
    path: 'inventory',
    name: 'AssetRegistry',
    title: 'Asset Registry',
    icon: 'inventory_2',
    showInSidebar: true,
    component: () => import('../views/AssetRegistry.vue'),
  },
  {
    path: 'consumables',
    name: 'ConsumablesSuppliesTracker',
    title: 'Consumables',
    icon: 'inventory',
    showInSidebar: true,
    component: () => import('../views/ConsumablesSuppliesTracker.vue'),
  },
  {
    path: 'work-order/:id',
    name: 'WorkOrderDetail',
    title: 'Work Order Detail',
    component: () => import('../views/WorkOrderDetail.vue'),
  },
  {
    path: 'audits',
    name: 'AuditSessions',
    title: 'Audit Sessions',
    icon: 'fact_check',
    showInSidebar: true,
    component: () => import('../views/AuditSessions.vue'),
  },
  {
    path: 'settings',
    name: 'UserManagementSettings',
    title: 'Settings',
    icon: 'settings',
    showInSidebar: true,
    component: () => import('../views/UserManagementSettings.vue'),
  },
  {
    path: 'financials',
    name: 'FinancialAnalyticsDashboard',
    title: 'Financials',
    icon: 'payments',
    showInSidebar: true,
    component: () => import('../views/FinancialAnalyticsDashboard.vue'),
  },
  {
    path: 'depreciation',
    name: 'AssetDepreciationLedger',
    title: 'Depreciation',
    icon: 'trending_down',
    showInSidebar: true,
    component: () => import('../views/AssetDepreciationLedger.vue'),
  },
  {
    path: 'licenses',
    name: 'SoftwareLicenseRegistry',
    title: 'Licenses',
    icon: 'verified_user',
    showInSidebar: true,
    component: () => import('../views/SoftwareLicenseRegistry.vue'),
  },
  {
    path: 'reservations',
    name: 'ReservationsBookings',
    title: 'Reservations',
    icon: 'event_available',
    showInSidebar: true,
    component: () => import('../views/ReservationsBookings.vue'),
  },
  {
    path: 'asset/:id',
    name: 'AssetDetail',
    title: 'Asset Detail',
    component: () => import('../views/AssetDetail.vue'),
  },
  {
    path: 'maintenance-contracts',
    name: 'MaintenanceContractsOverview',
    title: 'Maintenance Contracts',
    icon: 'contract_edit',
    showInSidebar: true,
    component: () => import('../views/MaintenanceContractsOverview.vue'),
  },
  {
    path: 'roles',
    name: 'UserAccessRoleControl',
    title: 'User Roles',
    icon: 'admin_panel_settings',
    showInSidebar: true,
    component: () => import('../views/UserAccessRoleControl.vue'),
  },
  {
    path: 'maintenance',
    name: 'MaintenanceScheduleContracts',
    title: 'Maintenance',
    icon: 'build_circle',
    showInSidebar: true,
    component: () => import('../views/MaintenanceScheduleContracts.vue'),
  },
  {
    path: 'maintenance-tracker',
    name: 'ScheduledMaintenanceTracker',
    title: 'Maintenance Tracker',
    icon: 'event_repeat',
    showInSidebar: true,
    component: () => import('../views/ScheduledMaintenanceTracker.vue'),
  },
  {
    path: 'maintenance-history',
    name: 'MaintenanceServiceHistoryLog',
    title: 'Service History',
    icon: 'history',
    showInSidebar: true,
    component: () => import('../views/MaintenanceServiceHistoryLog.vue'),
  },
  {
    path: 'audit-cleanup',
    name: 'AuditDiscrepancyResolution',
    title: 'Audit Cleanup',
    icon: 'rule_folder',
    showInSidebar: true,
    component: () => import('../views/AuditDiscrepancyResolution.vue'),
  },
  {
    path: 'report-builder',
    name: 'CustomReportBuilder',
    title: 'Report Builder',
    icon: 'edit_note',
    showInSidebar: true,
    component: () => import('../views/CustomReportBuilder.vue'),
  },
  {
    path: 'financial-ledger',
    name: 'FinancialLedgerDetail',
    title: 'Financial Ledger',
    component: () => import('../views/FinancialLedgerDetail.vue'),
  },
  {
    path: 'check-out',
    name: 'AssetCheckOutFlow',
    title: 'Asset Check Out',
    component: () => import('../views/AssetCheckOutFlow.vue'),
  },
  {
    path: 'check-out-assign',
    name: 'AssetCheckOutStep2',
    title: 'Check Out Assignment',
    component: () => import('../views/AssetCheckOutStep2.vue'),
  },
  {
    path: 'lease/:id',
    name: 'LeaseAgreementDetail',
    title: 'Lease Detail',
    component: () => import('../views/LeaseAgreementDetail.vue'),
  },
  {
    path: 'procurement/:id',
    name: 'ProcurementRequestDetail',
    title: 'Procurement Detail',
    component: () => import('../views/ProcurementRequestDetail.vue'),
  },
  {
    path: 'procurement',
    name: 'ProcurementPipeline',
    title: 'Procurement',
    icon: 'shopping_cart',
    showInSidebar: true,
    component: () => import('../views/ProcurementPipeline.vue'),
  },
  {
    path: 'audit-scan',
    name: 'AuditScanModeMobile',
    title: 'Audit Scan',
    component: () => import('../views/AuditScanModeMobile.vue'),
  },
  {
    path: 'add-asset',
    name: 'AddNewAssetForm',
    title: 'Add Asset',
    component: () => import('../views/AddNewAssetForm.vue'),
  },
  {
    path: 'self-service',
    name: 'EmployeeSelfServicePortal',
    title: 'Self Service',
    icon: 'person_pin',
    showInSidebar: true,
    component: () => import('../views/EmployeeSelfServicePortal.vue'),
  },
  {
    path: 'setup-wizard',
    name: 'SetupWizardLocationsConfiguration',
    title: 'Setup Wizard',
    icon: 'tune',
    showInSidebar: true,
    component: () => import('../views/SetupWizardLocationsConfiguration.vue'),
  },
  {
    path: 'reports',
    name: 'ReportsAnalyticsDashboard',
    title: 'Reports',
    icon: 'analytics',
    showInSidebar: true,
    component: () => import('../views/ReportsAnalyticsDashboard.vue'),
  },
  {
    path: 'stockrooms',
    name: 'StockroomInventory',
    title: 'Stockrooms',
    icon: 'warehouse',
    showInSidebar: true,
    component: () => import('../views/StockroomInventory.vue'),
  },
  {
    path: 'inventory-cards',
    name: 'InventoryCardView',
    title: 'Asset Cards',
    icon: 'grid_view',
    showInSidebar: true,
    component: () => import('../views/InventoryCardView.vue'),
  },
  {
    path: 'alerts',
    name: 'AlertsNotificationsCenter',
    title: 'Alerts',
    icon: 'notifications',
    showInSidebar: true,
    component: () => import('../views/AlertsNotificationsCenter.vue'),
  },
];

export const sidebarGroups = [
  {
    name: 'Inventory',
    items: [
      'AssetRegistry',
      'StockroomInventory',
      'ConsumablesSuppliesTracker',
      'SoftwareLicenseRegistry',
      'InventoryCardView',
    ],
  },
  {
    name: 'Operations',
    items: [
      'MaintenanceScheduleContracts',
      'ScheduledMaintenanceTracker',
      'AuditSessions',
      'ReservationsBookings',
      'MaintenanceContractsOverview',
      'MaintenanceServiceHistoryLog',
    ],
  },
  {
    name: 'Financials',
    items: ['ProcurementPipeline', 'FinancialAnalyticsDashboard', 'AssetDepreciationLedger'],
  },
  {
    name: 'Analytics',
    items: ['ReportsAnalyticsDashboard', 'CustomReportBuilder'],
  },
  {
    name: 'System',
    items: [
      'AlertsNotificationsCenter',
      'EmployeeSelfServicePortal',
      'UserAccessRoleControl',
      'SetupWizardLocationsConfiguration',
    ],
  },
];
